### ISSUE TITLE
zip opening problem

### ISSUE THREAD

**Issue by Janmm14** [ItzSomebody/StopDecompilingMyJava#8]
not sure if sfx zip is the problem (aka zip comment)

but i have a jar here which cannot be opened by helios, windows explorer and 7zip (maybe more), (winrar can open it, and bukkit can load it too)

**Comment by Janmm14** [comment]
or is this just issue 1?

**Comment by Janmm14** [comment]
Helios does not recognize that jar file as jar file and instead shows HEX of the jar

**Comment by ItzSomebody** [comment]
Is it possible that's due to an encoding issue? [Case in point](https://github.com/java-deobfuscator/deobfuscator/issues/358)

**Comment by Janmm14** [comment]
java-deobfuscator has no problem opening and editing the jar
unfortunaly i cannot share the jar file

**Comment by ItzSomebody** [comment]
Hmmm, might be some header hackery in that case.

**Comment by Janmm14** [comment]
actually i just had an old helios decompiler version, sorry
